SRC = $(wildcard src/*.c)
INPUT ?= $(wildcard inputs/*/*.x)
CFLAGS ?=
CPPUTEST_HOME = /usr/local/Cellar/cpputest/4.0
CPPUTEST_FLAGS = -I$(CPPUTEST_HOME)/include -L$(CPPUTEST_HOME)/lib -lCppUTest -lCppUTestExt -include $(CPPUTEST_HOME)/include/CppUTest/MemoryLeakDetectorMallocMacros.h
BENCHMARKS ?= $(wildcard inputs/benchmark/*.x)
LAB1_SUBMISSION_DIR = lab1-zikai-$(shell /bin/date "+%Y-%m-%d")

.PHONY: all verify clean

all: sim cache_test

sim: $(SRC)
	gcc $(CFLAGS) -g -O2 $^ -o $@

basesim: $(SRC)
	gcc $(CFLAGS) -g -O2 $^ -o $@

run: sim
	@python3 run.py $(INPUT)

cache_test: src/cache.c test/mock_mem.c test/cache_test.c test/test_main.cpp
	gcc $(CFLAGS) -g -O0 -c src/cache.c
	gcc -I$(CPPUTEST_HOME)/include -g -O0 -c test/mock_mem.c
	gcc -I$(CPPUTEST_HOME)/include -g -O0 -c test/cache_test.c
	g++ $(CPPUTEST_FLAGS) -g -O0 cache.o mock_mem.o cache_test.o test/test_main.cpp -o $@

sims: $(SRC)
	mkdir -p programs

	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=256 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_256_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=256 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_256_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=128 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_128_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=128 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_128_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=64 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_64_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=64 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_64_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=32 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_32_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=32 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_32_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=16 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_16_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=16 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_16_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=8 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_8_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=8 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_8_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=4 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_4_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=4 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_4_32_random
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=2 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_4_32_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=2 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_4_2_32_random

	gcc -DDATA_CACHE_WAY=1 -DDATA_CACHE_SET=128 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_1_128_32_lru
	gcc -DDATA_CACHE_WAY=1 -DDATA_CACHE_SET=128 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_1_128_32_random
	gcc -DDATA_CACHE_WAY=2 -DDATA_CACHE_SET=64 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_2_64_32_lru
	gcc -DDATA_CACHE_WAY=2 -DDATA_CACHE_SET=64 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_2_64_32_random
	gcc -DDATA_CACHE_WAY=8 -DDATA_CACHE_SET=16 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_8_16_32_lru
	gcc -DDATA_CACHE_WAY=8 -DDATA_CACHE_SET=16 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_8_16_32_random
	gcc -DDATA_CACHE_WAY=16 -DDATA_CACHE_SET=8 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_16_8_32_lru
	gcc -DDATA_CACHE_WAY=16 -DDATA_CACHE_SET=8 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_16_8_32_random
	gcc -DDATA_CACHE_WAY=32 -DDATA_CACHE_SET=4 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_32_4_32_lru
	gcc -DDATA_CACHE_WAY=32 -DDATA_CACHE_SET=4 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_32_4_32_random
	gcc -DDATA_CACHE_WAY=64 -DDATA_CACHE_SET=2 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_64_2_32_lru
	gcc -DDATA_CACHE_WAY=64 -DDATA_CACHE_SET=2 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_64_2_32_random
	gcc -DDATA_CACHE_WAY=128 -DDATA_CACHE_SET=1 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_128_1_32_lru
	gcc -DDATA_CACHE_WAY=128 -DDATA_CACHE_SET=1 -DDATA_CACHE_POLICY=RANDOM -g -O2 $^ -o programs/data_128_1_32_random

	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=64 -DDATA_CACHE_BLOCK=16 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_64_16_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=128 -DDATA_CACHE_BLOCK=8 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_128_8_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=256 -DDATA_CACHE_BLOCK=4 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_256_4_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=16 -DDATA_CACHE_BLOCK=64 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_16_64_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=8 -DDATA_CACHE_BLOCK=128 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_8_128_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=4 -DDATA_CACHE_BLOCK=256 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_4_256_lru
	gcc -DDATA_CACHE_WAY=4 -DDATA_CACHE_SET=2 -DDATA_CACHE_BLOCK=512 -DDATA_CACHE_POLICY=LRU -g -O2 $^ -o programs/data_4_2_512_lru

collect_data:
	@python3 collect_data.py $(BENCHMARKS)
	@#python3 collect_data.py inputs/benchmark/mergesort.x

clean:
	rm -rf *.o *~ sim cache_test *.dSYM

lab1_submission:
	@mkdir $(LAB1_SUBMISSION_DIR)
	@mkdir $(LAB1_SUBMISSION_DIR)/task_1
	@cp Makefile $(LAB1_SUBMISSION_DIR)/task_1
	@cp run.py $(LAB1_SUBMISSION_DIR)/task_1
	@cp collect_data.py $(LAB1_SUBMISSION_DIR)/task_1
	@cp -r src $(LAB1_SUBMISSION_DIR)/task_1
	@cp -r inputs $(LAB1_SUBMISSION_DIR)/task_1
	@cp -r test $(LAB1_SUBMISSION_DIR)/task_1
	@mkdir $(LAB1_SUBMISSION_DIR)/task_2
	@cp ../report_cache.pdf $(LAB1_SUBMISSION_DIR)/task_2
	@cp README.md $(LAB1_SUBMISSION_DIR)/
	@tar -czvf $(LAB1_SUBMISSION_DIR).tar.gz $(LAB1_SUBMISSION_DIR)
	@rm -rf $(LAB1_SUBMISSION_DIR)
